import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api, errorMessage } from '../api.js';
import { Alert, Field, bloodGroups } from '../components.jsx';

const checks = [['age','I am between 18 and 65 years old'],['weight','I weigh at least 50 kg'],['health','I am in good health and feeling well today'],['medication','I have not taken any medication in the last 24 hours'],['lastDonation','My last donation was more than 56 days ago']];
export default function Donate() {
  const navigate = useNavigate(); const [form, setForm] = useState({ bloodGroup: 'O+', medicalCheckupDate: '', eligibility: {} }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { await api.post('/donations', form); navigate('/dashboard', { state: { message: 'Thank you for your donation!' } }); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } };
  return <><div className="row justify-content-center"><div className="col-md-8"><div className="card shadow"><div className="card-body p-5"><h2 className="text-center mb-4">Blood Donation Form</h2><Alert>{error}</Alert><form onSubmit={submit}><Field label="Blood group" as="select" name="bloodGroup" value={form.bloodGroup} onChange={e => setForm({ ...form, bloodGroup: e.target.value })}>{bloodGroups.map(group => <option key={group}>{group}</option>)}</Field><Field label="Medical checkup date" name="medicalCheckupDate" type="date" max={new Date().toISOString().slice(0,10)} value={form.medicalCheckupDate} onChange={e => setForm({ ...form, medicalCheckupDate: e.target.value })} required /><div className="mb-4"><h5>Eligibility Checklist</h5>{checks.map(([key,label]) => <div className="form-check mb-2" key={key}><input className="form-check-input" type="checkbox" id={key} checked={Boolean(form.eligibility[key])} onChange={e => setForm({ ...form, eligibility: { ...form.eligibility, [key]: e.target.checked } })} required /><label className="form-check-label" htmlFor={key}>{label}</label></div>)}</div><div className="d-grid"><button className="btn btn-primary" disabled={busy}>{busy ? 'Submitting…' : 'Submit Donation'}</button></div></form></div></div></div></div><InfoCard items={['Get a good night’s sleep before donating','Eat a healthy meal before donation','Drink plenty of water','Bring a valid ID','Avoid fatty foods before donation']} /></>;
}
function InfoCard({ items }) { return <div className="row mt-4"><div className="col-12"><div className="card bg-light"><div className="card-body"><h5>Important Information</h5><ul className="list-unstyled">{items.map(item => <li key={item}><i className="fas fa-info-circle text-primary me-2" />{item}</li>)}</ul></div></div></div></div>; }
